### ISSUE TITLE
Keywords have same color as identifiers

### ISSUE THREAD

**Issue by screendriver** [binhtran432k/dracula.nvim#3]
For example this class:

<img width="223" alt="Screenshot 2024-03-06 at 13 00 34" src="https://github.com/binhtran432k/dracula.nvim/assets/149248/7f273549-acd2-446f-a135-ab8c0696f1a4">

looks like this with [dracula/vim](https://github.com/dracula/vim):

<img width="225" alt="Screenshot 2024-03-06 at 13 03 19" src="https://github.com/binhtran432k/dracula.nvim/assets/149248/0e3884be-1485-4531-aa7f-a2095ff7bdcd">

**Comment by binhtddev** [comment]
I apologize, but l am unable to reproduce this. What language are you using?

**Comment by screendriver** [comment]
This example was written in [Dart](https://dart.dev).

One interesting effect that I figured out: initially when I open Neovim the colors looks ok. But when I enter a new line (`O` key) following is happening:


![Screen Recording 2024-03-06 at 13 35 50](https://github.com/binhtran432k/dracula.nvim/assets/149248/e663501a-d874-4f9b-8822-2bdbcbda676d)

**Comment by binhtddev** [comment]
Ah, I understand the issue. You're using the stable version of NeoVim, while I haven't been able to reproduce this in the Nightly version. However, I've just applied a patch for the stable version as well. Please test it again; thank you for raising the issue.

**Comment by screendriver** [comment]
> I've just applied a patch for the stable version as well. Please test it again

I updated and it works as expected 👍 Thank you for the quick fix (and the great color scheme)!
